from django.core.management.base import BaseCommand

from djangoBack.armenify_server.models import Word


class Command(BaseCommand):
    help = "Seed Armenian A1 words into the Word table."

    def handle(self, *args, **options):
        words = [
            {"armenian": "բարեւ", "translations": ["привет"], "transcription": "barev"},
            {"armenian": "շնորհակալություն", "translations": ["спасибо"], "transcription": "shnorhakalutyun"},
            {"armenian": "խնդրում եմ", "translations": ["пожалуйста"], "transcription": "khndrum em"},
            {"armenian": "այո", "translations": ["да"], "transcription": "ayo"},
            {"armenian": "ոչ", "translations": ["нет"], "transcription": "voch"},
            {"armenian": "ներեցեք", "translations": ["извините"], "transcription": "neredzek"},
            {"armenian": "խոսք", "translations": ["слово"], "transcription": "khosk"},
            {"armenian": "մարդ", "translations": ["человек"], "transcription": "mard"},
            {"armenian": "կին", "translations": ["женщина"], "transcription": "kin"},
            {"armenian": "տղամարդ", "translations": ["мужчина"], "transcription": "tmard"},
            {"armenian": "երեխա", "translations": ["ребёнок", "ребенок"], "transcription": "yerexa"},
            {"armenian": "տուն", "translations": ["дом"], "transcription": "tun"},
            {"armenian": "դպրոց", "translations": ["школа"], "transcription": "dproc"},
            {"armenian": "դաս", "translations": ["урок", "класс"], "transcription": "das"},
            {"armenian": "գիրք", "translations": ["книга"], "transcription": "girk"},
            {"armenian": "գրիչ", "translations": ["ручка"], "transcription": "grich"},
            {"armenian": "սեղան", "translations": ["стол"], "transcription": "seghan"},
            {"armenian": "աթոռ", "translations": ["стул"], "transcription": "atorr"},
            {"armenian": "պատ", "translations": ["стена"], "transcription": "pat"},
            {"armenian": "դուռ", "translations": ["дверь"], "transcription": "dur"},
            {"armenian": "պատուհան", "translations": ["окно"], "transcription": "patuhan"},
            {"armenian": "ճանապարհ", "translations": ["дорога"], "transcription": "chanaparh"},
            {"armenian": "քաղաք", "translations": ["город"], "transcription": "qaxaq"},
            {"armenian": "գյուղ", "translations": ["деревня"], "transcription": "gyugh"},
            {"armenian": "փողոց", "translations": ["улица"], "transcription": "poghots"},
            {"armenian": "մեքենա", "translations": ["машина"], "transcription": "mekhena"},
            {"armenian": "ավտոբուս", "translations": ["автобус"], "transcription": "avtobus"},
            {"armenian": "տաք", "translations": ["тёплый", "теплый"], "transcription": "tak"},
            {"armenian": "սառը", "translations": ["холодный"], "transcription": "sarre"},
            {"armenian": "մեծ", "translations": ["большой"], "transcription": "mec"},
            {"armenian": "փոքր", "translations": ["маленький"], "transcription": "pokr"},
            {"armenian": "լավ", "translations": ["хороший"], "transcription": "lav"},
            {"armenian": "վատ", "translations": ["плохой"], "transcription": "vat"},
            {"armenian": "նոր", "translations": ["новый"], "transcription": "nor"},
            {"armenian": "հին", "translations": ["старый"], "transcription": "hin"},
            {"armenian": "օր", "translations": ["день"], "transcription": "or"},
            {"armenian": "գիշեր", "translations": ["ночь"], "transcription": "gisher"},
            {"armenian": "առավոտ", "translations": ["утро"], "transcription": "aravot"},
            {"armenian": "երեկո", "translations": ["вечер"], "transcription": "yereko"},
            {"armenian": "այսօր", "translations": ["сегодня"], "transcription": "aysor"},
            {"armenian": "վաղը", "translations": ["завтра"], "transcription": "vaghe"},
            {"armenian": "երեկ", "translations": ["вчера"], "transcription": "yerek"},
            {"armenian": "հիմա", "translations": ["сейчас"], "transcription": "hima"},
            {"armenian": "հետո", "translations": ["потом"], "transcription": "heto"},
            {"armenian": "առաջ", "translations": ["раньше", "впереди"], "transcription": "araj"},
            {"armenian": "աջ", "translations": ["право"], "transcription": "aj"},
            {"armenian": "ձախ", "translations": ["лево"], "transcription": "dzakh"},
            {"armenian": "վեր", "translations": ["вверх"], "transcription": "ver"},
            {"armenian": "ներքեւ", "translations": ["вниз"], "transcription": "nerkhev"},
            {"armenian": "մոտ", "translations": ["близко"], "transcription": "mot"},
            {"armenian": "հեռու", "translations": ["далеко"], "transcription": "heru"},
            {"armenian": "ժամ", "translations": ["час"], "transcription": "zham"},
            {"armenian": "րոպե", "translations": ["минута"], "transcription": "rope"},
            {"armenian": "վայրկյան", "translations": ["секунда"], "transcription": "vayrkyan"},
            {"armenian": "մեկ", "translations": ["один"], "transcription": "mek"},
            {"armenian": "երկու", "translations": ["два"], "transcription": "yerku"},
            {"armenian": "երեք", "translations": ["три"], "transcription": "yerek"},
            {"armenian": "չորս", "translations": ["четыре"], "transcription": "chors"},
            {"armenian": "հինգ", "translations": ["пять"], "transcription": "hing"},
            {"armenian": "վեց", "translations": ["шесть"], "transcription": "vec"},
            {"armenian": "յոթ", "translations": ["семь"], "transcription": "yot"},
            {"armenian": "ութ", "translations": ["восемь"], "transcription": "ut"},
            {"armenian": "իննը", "translations": ["девять"], "transcription": "inne"},
            {"armenian": "տաս", "translations": ["десять"], "transcription": "tas"},
            {"armenian": "կարմիր", "translations": ["красный"], "transcription": "karmir"},
            {"armenian": "կապույտ", "translations": ["синий", "голубой"], "transcription": "kapuyt"},
            {"armenian": "կանաչ", "translations": ["зелёный", "зеленый"], "transcription": "kanach"},
            {"armenian": "սեւ", "translations": ["чёрный", "черный"], "transcription": "sev"},
            {"armenian": "սպիտակ", "translations": ["белый"], "transcription": "spitak"},
            {"armenian": "դեղին", "translations": ["жёлтый", "желтый"], "transcription": "deghin"},
            {"armenian": "շագանակագույն", "translations": ["коричневый"], "transcription": "shaganakaguyn"},
            {"armenian": "ջուր", "translations": ["вода"], "transcription": "jur"},
            {"armenian": "հաց", "translations": ["хлеб"], "transcription": "hats"},
            {"armenian": "կաթ", "translations": ["молоко"], "transcription": "kat"},
            {"armenian": "թեյ", "translations": ["чай"], "transcription": "tey"},
            {"armenian": "սուրճ", "translations": ["кофе"], "transcription": "surj"},
            {"armenian": "աղ", "translations": ["соль"], "transcription": "agh"},
            {"armenian": "շաքար", "translations": ["сахар"], "transcription": "shakar"},
            {"armenian": "խնձոր", "translations": ["яблоко"], "transcription": "khndzor"},
            {"armenian": "բանան", "translations": ["банан"], "transcription": "banan"},
            {"armenian": "միս", "translations": ["мясо"], "transcription": "mis"},
            {"armenian": "ձուկ", "translations": ["рыба"], "transcription": "dzuk"},
            {"armenian": "ձու", "translations": ["яйцо"], "transcription": "dzu"},
            {"armenian": "պանիր", "translations": ["сыр"], "transcription": "panir"},
            {"armenian": "շուկա", "translations": ["рынок"], "transcription": "shuka"},
            {"armenian": "խանութ", "translations": ["магазин"], "transcription": "khanut"},
            {"armenian": "փող", "translations": ["деньги"], "transcription": "pox"},
            {"armenian": "ժամանակ", "translations": ["время"], "transcription": "zhamanak"},
            {"armenian": "անուն", "translations": ["имя"], "transcription": "anun"},
            {"armenian": "ընկեր", "translations": ["друг"], "transcription": "enker"},
            {"armenian": "ընտանիք", "translations": ["семья"], "transcription": "entanik"},
            {"armenian": "մայր", "translations": ["мать"], "transcription": "mayr"},
            {"armenian": "հայր", "translations": ["отец"], "transcription": "hayr"},
            {"armenian": "եղբայր", "translations": ["брат"], "transcription": "yeghbayr"},
            {"armenian": "քույր", "translations": ["сестра"], "transcription": "kuir"},
            {"armenian": "աշխատել", "translations": ["работать"], "transcription": "ashkhatel"},
            {"armenian": "գնալ", "translations": ["идти", "поехать"], "transcription": "gnal"},
            {"armenian": "գալ", "translations": ["приходить", "прибывать"], "transcription": "gal"},
            {"armenian": "տեսնել", "translations": ["видеть"], "transcription": "tesnel"},
            {"armenian": "լսել", "translations": ["слышать"], "transcription": "lsel"},
        ]

        Word.objects.all().delete()
        Word.objects.bulk_create(
            [
                Word(
                    armenian=w["armenian"],
                    translations=w["translations"],
                    transcription=w["transcription"],
                    level="A1",
                )
                for w in words
            ]
        )
        self.stdout.write(self.style.SUCCESS(f"Inserted {len(words)} words"))
