# Generated by Django 6.0.1 on 2026-02-19 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('armenify_server', '0003_wordcomment'),
        ('armenify_server', '0004_userchathistory'),
    ]

    operations = [
    ]
