from django.core.management.base import BaseCommand

from ArmenifyMe.armenify_server.models import Word


class Command(BaseCommand):
    help = "Seed Armenian A1 words into the Word table."

    def handle(self, *args, **options):
        words = [
            {"armenian": "?????", "translations": ["привет"], "transcription": "barev"},
            {"armenian": "????????????????", "translations": ["спасибо"], "transcription": "shnorhakalutyun"},
            {"armenian": "??????? ??", "translations": ["пожалуйста"], "transcription": "khndrum em"},
            {"armenian": "???", "translations": ["да"], "transcription": "ayo"},
            {"armenian": "??", "translations": ["нет"], "transcription": "voch"},
            {"armenian": "???????", "translations": ["извините"], "transcription": "neredzek"},
            {"armenian": "????", "translations": ["слово"], "transcription": "khosk"},
            {"armenian": "????", "translations": ["человек"], "transcription": "mard"},
            {"armenian": "???", "translations": ["женщина"], "transcription": "kin"},
            {"armenian": "???????", "translations": ["мужчина"], "transcription": "tmard"},
            {"armenian": "?????", "translations": ["ребЄнок", "ребенок"], "transcription": "yerexa"},
            {"armenian": "????", "translations": ["дом"], "transcription": "tun"},
            {"armenian": "?????", "translations": ["школа"], "transcription": "dproc"},
            {"armenian": "???", "translations": ["урок", "класс"], "transcription": "das"},
            {"armenian": "????", "translations": ["книга"], "transcription": "girk"},
            {"armenian": "????", "translations": ["ручка"], "transcription": "grich"},
            {"armenian": "?????", "translations": ["стол"], "transcription": "seghan"},
            {"armenian": "????", "translations": ["стул"], "transcription": "atorr"},
            {"armenian": "???", "translations": ["стена"], "transcription": "pat"},
            {"armenian": "????", "translations": ["дверь"], "transcription": "dur"},
            {"armenian": "????????", "translations": ["окно"], "transcription": "patuhan"},
            {"armenian": "????????", "translations": ["дорога"], "transcription": "chanaparh"},
            {"armenian": "?????", "translations": ["город"], "transcription": "qaxaq"},
            {"armenian": "?????", "translations": ["деревн€"], "transcription": "gyugh"},
            {"armenian": "?????", "translations": ["улица"], "transcription": "poghots"},
            {"armenian": "??????", "translations": ["машина"], "transcription": "mekhena"},
            {"armenian": "????????", "translations": ["автобус"], "transcription": "avtobus"},
            {"armenian": "???", "translations": ["тЄплый", "теплый"], "transcription": "tak"},
            {"armenian": "????", "translations": ["холодный"], "transcription": "sarre"},
            {"armenian": "???", "translations": ["большой"], "transcription": "mec"},
            {"armenian": "????", "translations": ["маленький"], "transcription": "pokr"},
            {"armenian": "???", "translations": ["хороший"], "transcription": "lav"},
            {"armenian": "???", "translations": ["плохой"], "transcription": "vat"},
            {"armenian": "???", "translations": ["новый"], "transcription": "nor"},
            {"armenian": "???", "translations": ["старый"], "transcription": "hin"},
            {"armenian": "??", "translations": ["день"], "transcription": "or"},
            {"armenian": "?????", "translations": ["ночь"], "transcription": "gisher"},
            {"armenian": "??????", "translations": ["утро"], "transcription": "aravot"},
            {"armenian": "?????", "translations": ["вечер"], "transcription": "yereko"},
            {"armenian": "?????", "translations": ["сегодн€"], "transcription": "aysor"},
            {"armenian": "????", "translations": ["завтра"], "transcription": "vaghe"},
            {"armenian": "????", "translations": ["вчера"], "transcription": "yerek"},
            {"armenian": "????", "translations": ["сейчас"], "transcription": "hima"},
            {"armenian": "????", "translations": ["потом"], "transcription": "heto"},
            {"armenian": "????", "translations": ["раньше", "впереди"], "transcription": "araj"},
            {"armenian": "??", "translations": ["право"], "transcription": "aj"},
            {"armenian": "???", "translations": ["лево"], "transcription": "dzakh"},
            {"armenian": "???", "translations": ["вверх"], "transcription": "ver"},
            {"armenian": "??????", "translations": ["вниз"], "transcription": "nerkhev"},
            {"armenian": "???", "translations": ["близко"], "transcription": "mot"},
            {"armenian": "?????", "translations": ["далеко"], "transcription": "heru"},
            {"armenian": "???", "translations": ["час"], "transcription": "zham"},
            {"armenian": "????", "translations": ["минута"], "transcription": "rope"},
            {"armenian": "????????", "translations": ["секунда"], "transcription": "vayrkyan"},
            {"armenian": "???", "translations": ["один"], "transcription": "mek"},
            {"armenian": "?????", "translations": ["два"], "transcription": "yerku"},
            {"armenian": "????", "translations": ["три"], "transcription": "yerek"},
            {"armenian": "????", "translations": ["четыре"], "transcription": "chors"},
            {"armenian": "????", "translations": ["п€ть"], "transcription": "hing"},
            {"armenian": "???", "translations": ["шесть"], "transcription": "vec"},
            {"armenian": "???", "translations": ["семь"], "transcription": "yot"},
            {"armenian": "???", "translations": ["восемь"], "transcription": "ut"},
            {"armenian": "????", "translations": ["дев€ть"], "transcription": "inne"},
            {"armenian": "???", "translations": ["дес€ть"], "transcription": "tas"},
            {"armenian": "??????", "translations": ["красный"], "transcription": "karmir"},
            {"armenian": "???????", "translations": ["синий", "голубой"], "transcription": "kapuyt"},
            {"armenian": "?????", "translations": ["зелЄный", "зеленый"], "transcription": "kanach"},
            {"armenian": "???", "translations": ["чЄрный", "черный"], "transcription": "sev"},
            {"armenian": "??????", "translations": ["белый"], "transcription": "spitak"},
            {"armenian": "?????", "translations": ["жЄлтый", "желтый"], "transcription": "deghin"},
            {"armenian": "?????????????", "translations": ["коричневый"], "transcription": "shaganakaguyn"},
            {"armenian": "????", "translations": ["вода"], "transcription": "jur"},
            {"armenian": "???", "translations": ["хлеб"], "transcription": "hats"},
            {"armenian": "???", "translations": ["молоко"], "transcription": "kat"},
            {"armenian": "???", "translations": ["чай"], "transcription": "tey"},
            {"armenian": "?????", "translations": ["кофе"], "transcription": "surj"},
            {"armenian": "??", "translations": ["соль"], "transcription": "agh"},
            {"armenian": "?????", "translations": ["сахар"], "transcription": "shakar"},
            {"armenian": "?????", "translations": ["€блоко"], "transcription": "khndzor"},
            {"armenian": "?????", "translations": ["банан"], "transcription": "banan"},
            {"armenian": "???", "translations": ["м€со"], "transcription": "mis"},
            {"armenian": "????", "translations": ["рыба"], "transcription": "dzuk"},
            {"armenian": "???", "translations": ["€йцо"], "transcription": "dzu"},
            {"armenian": "?????", "translations": ["сыр"], "transcription": "panir"},
            {"armenian": "?????", "translations": ["рынок"], "transcription": "shuka"},
            {"armenian": "??????", "translations": ["магазин"], "transcription": "khanut"},
            {"armenian": "???", "translations": ["деньги"], "transcription": "pox"},
            {"armenian": "???????", "translations": ["врем€"], "transcription": "zhamanak"},
            {"armenian": "?????", "translations": ["им€"], "transcription": "anun"},
            {"armenian": "?????", "translations": ["друг"], "transcription": "enker"},
            {"armenian": "???????", "translations": ["семь€"], "transcription": "entanik"},
            {"armenian": "????", "translations": ["мать"], "transcription": "mayr"},
            {"armenian": "????", "translations": ["отец"], "transcription": "hayr"},
            {"armenian": "??????", "translations": ["брат"], "transcription": "yeghbayr"},
            {"armenian": "?????", "translations": ["сестра"], "transcription": "kuir"},
            {"armenian": "???????", "translations": ["работать"], "transcription": "ashkhatel"},
            {"armenian": "????", "translations": ["идти", "поехать"], "transcription": "gnal"},
            {"armenian": "???", "translations": ["приходить", "прибывать"], "transcription": "gal"},
            {"armenian": "??????", "translations": ["видеть"], "transcription": "tesnel"},
            {"armenian": "????", "translations": ["слышать"], "transcription": "lsel"},
        ]

        Word.objects.all().delete()
        Word.objects.bulk_create(
            [
                Word(
                    armenian=w["armenian"],
                    translations=w["translations"],
                    transcription=w["transcription"],
                    level="A1",
                )
                for w in words
            ]
        )
        self.stdout.write(self.style.SUCCESS(f"Inserted {len(words)} words"))
